Datasets:
  - Identifier: local
    Title: "Local HIGHROC OLCI L2C cube for region SNS"
    FileSystem: "local"
    Path: "cube.nc"
    #Path: "C:/Users/Norman/EOData/DCS4COP/OLCI-SNS-RAW-CUBE.zarr"
    #Format: zarr
    Style: default
    Places:
      - Identifier: cube-box
        BBox: [0, 50, 2, 52]
        Places:
        - RefId: inside-cube
      - RefId: outside-cube
#    # CyanoAlert Places
#    BoundingBox: [0, 50, 2, 52]
#    Places:
#      - Identifier: region
#        Path: "features/germany.geojson"
#        Places:
#        - Identifier: lakes
#          Path: "features/germany/lakes.geojson"
#          Places:
#          -  Identifier: stations
#             Path: "features/germany/lakes/${LAKE_ID}-stations.geojson"

#  - Identifier: remote
#    Title: "Remote HIGHROC OLCI L2C cube for region SNS"
#    Endpoint: "http://obs.eu-de.otc.t-systems.com"
#    Path: "dcs4cop-obs-01/OLCI-SNS-RAW-CUBE-2.zarr"
#    FileSystem: "obs"
#    Region: "eu-de"
#    Style: default

  - Identifier: computed
    Title: "Computed HIGHROC OLCI weekly L3 cube for region SNS"
    FileSystem: "computed"
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    #Args: ["@remote@", "1W"]
    Args: ["@local@", "1W"]
    Style: default

Features:
  - Identifier: inside-cube
    Title: Points inside the cube
    Path: "features/inside-cube.geojson"
  - Identifier: outside-cube
    Title: Points outside the cube
    Path: "features/outside-cube.geojson"

Places:
  - Identifier: inside-cube
    Title: Points inside the cube
    Path: "features/inside-cube.geojson"
  - Identifier: outside-cube
    Title: Points outside the cube
    Path: "features/outside-cube.geojson"

Styles:
  - Identifier: default
    ColorMappings:
      conc_chl:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
      conc_tsm:
        ColorBar: "PuBuGn"
        ValueRange: [0., 100.]
      kd489:
        ColorBar: "jet"
        ValueRange: [0., 6.]


ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"

