Datasets:
  - Identifier: local
    Title: "danube"
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: "local"
    Path: "/home/alicja/Desktop/DCS4COP/cyanoalert-olci-dan-l2c-v1.zarr"
    #Path: "C:/Users/Norman/EOData/DCS4COP/OLCI-SNS-RAW-CUBE.zarr"
    Format: zarr
    Style: default
#    PlaceGroups:
#      - PlaceGroupRef: inside-cube
#      - PlaceGroupRef: outside-cube

#    # CyanoAlert Places
#    BoundingBox: [0, 50, 5, 52.5]
#    PlaceGroups:
#      - Identifier: region
#        Path: "places/germany.geojson"
#        Places:
#        - Identifier: lakes
#          Path: "places/germany/lakes.geojson"
#          Places:
#          -  Identifier: stations
#             Path: "places/germany/lakes/${LAKE_ID}-stations.geojson"

#  - Identifier: remote
#    Title: "Remote HIGHROC OLCI L2C cube for region SNS"
#    BoundingBox: [0.0, 50, 5.0, 52.5]
#    Endpoint: "http://obs.eu-de.otc.t-systems.com"
#    Path: "dcs4cop-obs-01/OLCI-SNS-RAW-CUBE-2.zarr"
#    FileSystem: "obs"
#    Region: "eu-de"
#    Style: default
#    PlaceGroups:
#      - PlaceGroupRef: inside-cube
#      - PlaceGroupRef: outside-cube

  - Identifier: computed
    Title: "Danube Weekly"
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: "computed"
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    #Args: ["@remote@", "1W"]
    Args: ["@local@", "1W"]
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube

PlaceGroups:
  - Identifier: inside-cube
    Title: Points inside the cube
    Path: "places/inside-cube.geojson"
  - Identifier: outside-cube
    Title: Points outside the cube
    Path: "places/outside-cube.geojson"

Styles:
  - Identifier: default
    ColorMappings:
      chl_mph:
        ColorBar: "chl"
        ValueRange: [0., 200.]
      tsm_c2rcc:
        ColorBar: "tsm"
        ValueRange: [0., 100.]
      tur_nechad_665:
        ColorBar: "sdd"
        ValueRange: [0., 6.]


ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"

