Datasets:

  - Identifier: s2p
    Title: "S2+"
    FileSystem: local
    Path: "D:\\Projects\\xcube\\xcube\\cli\\PROJ_WGS84_DCS4COP_S2A_0021_FLANDERS_20180802T105621Z_31UCS_V003.zarr"
    Format: zarr
    # Path: "D:\\Projects\\xcube\\xcube\\cli\\PROJ_WGS84_DCS4COP_S2A_0021_FLANDERS_20180802T105621Z_31UCS_V003.levels"
    # Format: levels
    Style: default

  - Identifier: Sweden_SE
    Title: Sverige
    FileSystem: local
    Path: "C:\\Users\\Norman\\Brockmann Consult GmbH\\CyanoAlert Project Site - Data\\OLCI-SE-L2C-CUBE-v2-20180708_1_500_509.zarr"
    Format: zarr
    Style: default
    PlaceGroups:
      - PlaceGroupRef: Sweden_SE_Lakes

  - Identifier: Sweden_SE_1W
    Title: Sverige 1W
    Style: default
    FileSystem: memory
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    InputDatasets: ["Sweden_SE"]
    PlaceGroups:
      - PlaceGroupRef: Sweden_SE_Lakes


PlaceGroups:
  - Identifier: Sweden_SE_Lakes
    Title: "Svenska Sj\u00f6arna"
    Path: "places/Sweden-Lakes.geojson"
    CharacterEncoding: utf-8
    PropertyMapping:
      label: "SJONAMN"
      infoUrl: "URL_VISS"
  - Identifier: German_SH_Lakes
    Title: "Seen in SH"
    Path: "places/Germany-SH-Lakes.geojson"
    PropertyMapping:
      label: "S_NAME"
      infoUrl: "METADATA_U"
  - Identifier: German_SH_Stations
    Title: "Stationen in SH"
    Path: "places/Germany-SH-Stations.geojson"
    PropertyMapping:
      label: "Name"


Styles:
  - Identifier: default
    ColorMappings:
      rrs_443:
        ColorBar: "gray"
        ValueRange: [0., 0.03]
      conc_chl:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
      chl_c2rcc:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
      conc_tsm:
        ColorBar: "PuBuGn"
        ValueRange: [0., 100.]
      kd489:
        ColorBar: "jet"
        ValueRange: [0., 6.]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"

