Datasets:
  - Identifier: local
    Title: "Local OLCI L2C cube for region SNS"
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: local
    Path: "cube.nc"
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube

  - Identifier: remote
    Title: Remote OLCI L2C cube for region SNS
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: obs
    Endpoint: "http://obs.eu-de.otc.t-systems.com"
    Path: "dcs4cop-obs-01/OLCI-SNS-RAW-CUBE-2.zarr"
    Region: "eu-de"
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube

  - Identifier: local_1w
    Title: OLCI weekly L3 cube for region SNS computed from local L2C cube
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: memory
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    InputDatasets: ["local"]
    InputParameters:
      period: "1W"
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube

  - Identifier: remote_1w
    Title: OLCI weekly L3 cube for region SNS computed from remote L2C cube
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: memory
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    InputDatasets: ["remote"]
    InputParameters:
      period: "1W"
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube

PlaceGroups:
  - Identifier: inside-cube
    Title: Points inside the cube
    Path: "places/inside-cube.geojson"
  - Identifier: outside-cube
    Title: Points outside the cube
    Path: "places/outside-cube.geojson"

Styles:
  - Identifier: default
    ColorMappings:
      conc_chl:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
      conc_tsm:
        ColorBar: "PuBuGn"
        ValueRange: [0., 100.]
      kd489:
        ColorBar: "jet"
        ValueRange: [0., 6.]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"

